### ISSUE TITLE
Practica 1 Mockup

### ISSUE THREAD

**Issue by Aylin67** [SistemasTecTlaxiaco/actividad-1-practicaprototipo-equipo_eaaj#2]
Reporte
[ACTIVIDAD 1- MOCKUP DE INTERFAZ GRÁFICA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-practicaprototipo-equipo_eaaj/files/14283823/ACTIVIDAD.1-.MOCKUP.DE.INTERFAZ.GRAFICA.pdf)
Diseño
https://www.figma.com/file/DGvywbvYdUrcjsAidO08Vj/ProyectoBiblioteca?type=design&node-id=0%3A1&mode=design&t=18WHOzoasWt9fS8I-1
Integrantes
Elisabet Rojas Dominguez
Jessica Reyes Rosario
Ivonne Aylin Cuevas López
Antonia María Santos García

**Comment by Kim-Mendoza3** [comment]
Calificacion 90
En todo su desarrollo de reporte si se logró explicar todo lo que realizaron pero en la conclusion falto agregar que es lo que aprendieron durante la realizacion de su mockup.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
